Repository slide-rs/specs, pull requests merged in 2018-05, with the labels that each got.

#378 Doc fixes
  book/src/04_resources.md
  book/src/06_system_data.md
  book/src/07_join.md
  src/error.rs
  src/join.rs
  src/lib.rs
  src/saveload/marker.rs
  src/saveload/mod.rs
  src/saveload/ser.rs
  src/storage/data.rs
  src/world/entity.rs
  src/world/lazy.rs
Labels: ready

#392 refactor: Change LazyUpdate::execute to LazyUpdate::exec to follow co…
  src/world/lazy.rs
  src/world/tests.rs
Labels: ready

#395 book: Add a chapter about advanced component strategies
  book/src/02_hello_world.md
  book/src/11_advanced_component.md
  book/src/SUMMARY.md
Labels: docs, ready

#396 Do some cleanup, remove deprecated API
  Cargo.toml
  README.md
  examples/saveload.rs
  examples/serialize.rs
  src/storage/mod.rs
  src/storage/ser.rs
  src/storage/tests.rs
Labels: ready

#411 Make the book build again
  book/book.toml
  book/src/SUMMARY.md
Labels: bug

#415 Increase tuple size for SerializeComponents/DeserializeComponents
  src/saveload/de.rs
  src/saveload/ser.rs
Labels: ready

#418 Bump version to 0.11.1, update log
  CHANGELOG.md
  Cargo.toml
Labels: ready

#432 Fix bench warnings and disable autobenches
  Cargo.toml
  benches/parallel.rs
  benches/storage_cmp.rs
  benches/storage_sparse.rs
  benches/world.rs
Labels: ready

#429 Format and mark unsafe functions as such
  CHANGELOG.md
  examples/common.rs
  specs-derive/src/lib.rs
  src/bitset.rs
  src/changeset.rs
  src/common.rs
  src/join.rs
  src/lib.rs
  src/prelude.rs
  src/saveload/marker.rs
  src/saveload/tests.rs
  src/storage/drain.rs
  src/storage/flagged.rs
  src/storage/mod.rs
  src/storage/restrict.rs
  src/storage/track.rs
  src/world/entity.rs
  src/world/mod.rs
Labels: ready, soundness
