Repository slide-rs/specs, pull requests merged in 2018-02, with the labels that each got.

#343 Upgrade syn and quote, rename component attrib to storage
  specs-derive/Cargo.toml
  specs-derive/src/lib.rs
  src/lib.rs
Labels: enhancement, ready

#345 Add lines of code badge
  README.md
Labels: enhancement, ready

#344 feat: Add ChangeSet that can be collected into from iterators, and joined over for easy application to components
  specs-derive/src/lib.rs
  src/changeset.rs
  src/error.rs
  src/lib.rs
  src/prelude.rs
  src/storage/mod.rs
  src/storage/restrict.rs
  src/storage/tests.rs
Labels: enhancement, in progress

#349 Fix a couple of warnings
  src/common.rs
  src/world/mod.rs
Labels: enhancement

#350 Remove duplicated reference to docs.rs
  book/src/01_intro.md
Labels: docs

#348 Use criterion.rs for benchmarks
  .gitignore
  .travis.yml
  Cargo.toml
  README.md
  benches/benches_main.rs
  benches/storage.rs
  benches/storage_cmp.rs
  benches/storage_sparse.rs
  benches/world.rs
Labels: enhancement, ready

#356 Improve parallel join chapter in the book.
  book/src/08_parallel_join.md
Labels: docs
