Repository slide-rs/specs, pull requests merged in 2018-09, with the labels that each got.

#458 Bump version to 0.12.2
  CHANGELOG.md
  Cargo.toml
Labels: ready

#459 Fix repo link of specs-derive and bump version
  specs-derive/Cargo.toml
Labels: ready

#457 Reduced the complexity of the entity allocator
  Cargo.toml
  benches/world.rs
  src/world/entity.rs
Labels: ready

#465 Remove coveralls badge
  README.md
Labels: ready

#466 Update deps, examples and bump version
  CHANGELOG.md
  Cargo.toml
  examples/cluster_bomb.rs
  examples/full.rs
Labels: ready

#474 Use `fetch_mut` in book chapter 7, `setup`
  book/src/07_setup.md
Labels: docs

#447 Use non-zero optimization for Generation
  CHANGELOG.md
  Cargo.toml
  src/lib.rs
  src/storage/mod.rs
  src/world/entity.rs
  src/world/mod.rs
Labels: postponed

#481 Add missing joins
  book/src/11_advanced_component.md
Labels: ready
